### ISSUE TITLE
Alternative WORKDIR

### ISSUE THREAD

**Issue by jonioni** [bitnami/bitnami-docker-cluster-autoscaler#5]
**Description**

Suggest that `WORKDIR` be set to `/opt/bitnami/cluster-autoscaler/bin` which won't affect the default command, but would make the image compatible with the official [cluster-autoscaler helm chart](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler) which uses command: `./cluster-autoscaler ...`.

**Steps to reproduce the issue:**

1. Use helm chart "cluster-autoscaler" of repo "https://kubernetes.github.io/autoscaler".
2. Set helm chart config `image.repository` to "bitnami/cluster-autoscaler` (with tag name fixed).

**Describe the results you received:**

```bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./cluster-autoscaler": stat ./cluster-autoscaler: no such file or directory: unknown.
```

**Describe the results you expected:**

```bash
I0210 03:39:59.023614       1 flags.go:52] FLAG: --add-dir-header="false"
I0210 03:39:59.023690       1 flags.go:52] FLAG: --address=":8085"
I0210 03:39:59.023709       1 flags.go:52] FLAG: --alsologtostderr="false"
I0210 03:39:59.023728       1 flags.go:52] FLAG: --aws-use-static-instance-list="false"
I0210 03:39:59.023747       1 flags.go:52] FLAG: --balance-similar-node-groups="false"
I0210 03:39:59.024105       1 flags.go:52] FLAG: --cloud-config=""
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Kubernetes: v1.18+ 
Helm: v3+
[cluster-autoscaler Helm Chart](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler): v1.18.1, latest

**Comment by andresbono** [comment]
Hi @jonioni, instead of changing the `WORKDIR`, we usually create a symlink to ensure compatibility. For example:

https://github.com/bitnami/bitnami-docker-grafana-operator/blob/5ad02cc02d429a7626a7c74912f4e3618bdc6e90/3/debian-10/Dockerfile#L17
```Dockerfile
RUN ln -sf /opt/bitnami/grafana-operator/bin/grafana-operator /usr/local/bin/grafana-operator
```

Will that work for your use case?

**Comment by jonioni** [comment]
Thanks @andresbono . The main issue is about the integration with the official [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler) Helm chart which enables the usage of bitnami cluster-autoscaler image but not the change of the starting command `./cluster-autoscaler ...` (which implies that the binary is in the default work dir).

It would be great if bitnami cluster-autoscaler could support such integration, either by setting `WORKDIR  /opt/bitnami/cluster-autoscaler/bin` or creating a symlink in the current `WORKDIR` (for the `./cluster-autoscaler` reference).

**Comment by andresbono** [comment]
Hi @jonioni, `bitnami/cluster-autoscaler:1.20.0-debian-10-r54` https://github.com/bitnami/bitnami-docker-cluster-autoscaler/commit/92accb377ebb2a929521781a5d88aa7be5beba60 should solve the issue.

https://github.com/bitnami/bitnami-docker-cluster-autoscaler/blob/92accb377ebb2a929521781a5d88aa7be5beba60/1/debian-10/Dockerfile#L17

Can you give it a try and let us know?

**Comment by jonioni** [comment]
Works like a charm. Thanks for the quick response!
